Update build-firmware.yml

diff --git a/.github/workflows/build-firmware.yml b/.github/workflows/build-firmware.yml
--- a/.github/workflows/build-firmware.yml
+++ b/.github/workflows/build-firmware.yml
@@ -27,7 +27,10 @@ jobs:
         persist-credentials: false
 
     - name: Build firmware
-      run: for keymap in users/${{ github.actor }}/keymaps/*.json; do qmk compile "$keymap"; done
+      run: |
+          for keymap in users/${{ github.actor }}/keymaps/*.json; do
+              qmk compile "$keymap" || echo "ERROR: Failed to build $keymap!"
+          done
     - name: Upload artifacts
       uses: actions/upload-artifact@v2
       with:
